namespace TRIZMA.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;


    public partial class uhsA360modelLargeDb
    {
        [Key]
        public string AYID { get; set; }
        public int AYprojid { get; set; }
        public int AYtskoid { get; set; }
        public int AYdcgrid { get; set; }
        public int AYdctpid { get; set; }
        public int AYtspdid { get; set; }
        public int AYdistid { get; set; }
        public string AYdistnm { get; set; }
        public int AYacctid { get; set; }
        public int AYuserid { get; set; }
        public string AYusernm { get; set; }
        public int AYdimgid { get; set; }
        public string AYdimgnm { get; set; }
        public int AYsmid111 { get; set; }
        public string AYcmdt111 { get; set; }
        public int AYverf111 { get; set; }
        public int AYsmid112 { get; set; }
        public string AYcmdt112 { get; set; }
        public int AYverf112 { get; set; }
        public int AYsmid113 { get; set; }
        public string AYcmdt113 { get; set; }
        public int AYverf113 { get; set; }
        public int AYsmid114 { get; set; }
        public string AYcmdt114 { get; set; }
        public int AYverf114 { get; set; }
        public int AYsmid115 { get; set; }
        public string AYcmdt115 { get; set; }
        public int AYverf115 { get; set; }
        public int AYsmid116 { get; set; }
        public string AYcmdt116 { get; set; }
        public int AYverf116 { get; set; }
        public int AYsmid117 { get; set; }
        public string AYcmdt117 { get; set; }
        public int AYverf117 { get; set; }
        public int AYsmid118 { get; set; }
        public string AYcmdt118 { get; set; }
        public int AYverf118 { get; set; }
        public int AYsmid119 { get; set; }
        public string AYcmdt119 { get; set; }
        public int AYverf119 { get; set; }
        public int AYsmid120 { get; set; }
        public string AYcmdt120 { get; set; }
        public int AYverf120 { get; set; }
        public int AYsmid121 { get; set; }
        public string AYcmdt121 { get; set; }
        public int AYverf121 { get; set; }
        public int AYsmid122 { get; set; }
        public string AYcmdt122 { get; set; }
        public int AYverf122 { get; set; }
        public int AYsmid123 { get; set; }
        public string AYcmdt123 { get; set; }
        public int AYverf123 { get; set; }
        public int AYsmid124 { get; set; }
        public string AYcmdt124 { get; set; }
        public int AYverf124 { get; set; }
        public int AYsmid125 { get; set; }
        public string AYcmdt125 { get; set; }
        public int AYverf125 { get; set; }
        public string AYnote01 { get; set; }
        public string AYnote02 { get; set; }
        public string AYnote03 { get; set; }
        public string AYnote04 { get; set; }
        public string AYnote05 { get; set; }
        public string AYnote06 { get; set; }
        public string AYnote07 { get; set; }
        public string AYnote08 { get; set; }
        public string AYnote09 { get; set; }
        public string AYnote10 { get; set; }
        public string AYnote11 { get; set; }
        public string AYnote12 { get; set; }
        public string AYnote13 { get; set; }
        public string AYnote14 { get; set; }
        public string AYnote15 { get; set; }
        public string AYtask01 { get; set; }
        public string AYtask02 { get; set; }
        public string AYtask03 { get; set; }
        public string AYtask04 { get; set; }
        public string AYtask05 { get; set; }
        public string AYacit01 { get; set; }
        public string AYacit02 { get; set; }
        public string AYacit03 { get; set; }
        public string AYacit04 { get; set; }
        public string AYacit05 { get; set; }
        public string AYtool01 { get; set; }
        public string AYtool02 { get; set; }
        public string AYtool03 { get; set; }
        public string AYtool04 { get; set; }
        public string AYtool05 { get; set; }
        public string AYdocn01 { get; set; }
        public string AYdocn02 { get; set; }
        public string AYdocn03 { get; set; }
        public string AYdocn04 { get; set; }
        public string AYdocn05 { get; set; }
        public int AYprfx01 { get; set; }
        public int AYprfx02 { get; set; }
        public int AYprfx03 { get; set; }
        public int AYprfx04 { get; set; }
        public int AYprfx05 { get; set; }
        public string AYrate01 { get; set; }
        public string AYrate02 { get; set; }
        public string AYrate03 { get; set; }
        public string AYrate04 { get; set; }
        public string AYrate05 { get; set; }
        public string AYpref01 { get; set; }
        public string AYpref02 { get; set; }
        public string AYpref03 { get; set; }
        public string AYpref04 { get; set; }
        public string AYpref05 { get; set; }
        public string AYratd01 { get; set; }
        public string AYratd02 { get; set; }
        public string AYratd03 { get; set; }
        public string AYratd04 { get; set; }
        public string AYratd05 { get; set; }
        public int AYallch1c { get; set; }
        public int AYwekday { get; set; }
        public string AYwekdnm { get; set; }
        public bool AYchck { get; set; }
        public int AYchckid { get; set; }
        public string AYchcknm { get; set; }
        public string AYchckdt { get; set; }
        public int AYyyyy { get; set; }
        public int AYyyyymm { get; set; }
        public int AYweeknr { get; set; }
        public string AYweekds { get; set; }
        public int AYyyyymmdd { get; set; }
        public int AYhhmmss { get; set; }
        public string AYcrdt { get; set; }
        public string AYeddt { get; set; }
        public int AYcrusid { get; set; }
        public int AYedusid { get; set; }
        public string AYcrusnm { get; set; }
        public string AYedusnm { get; set; }
        public string AYcrdate { get; set; }

        public string BYID { get; set; }
        public int BYprojid { get; set; }
        public int BYtskoid { get; set; }
        public int BYdcgrid { get; set; }
        public int BYdctpid { get; set; }
        public int BYtspdid { get; set; }
        public int BYdistid { get; set; }
        public string BYdistnm { get; set; }
        public int BYacctid { get; set; }
        public int BYuserid { get; set; }
        public string BYusernm { get; set; }
        public int BYdimgid { get; set; }
        public string BYdimgnm { get; set; }
        public int BYsmid111 { get; set; }
        public string BYcmdt111 { get; set; }
        public int BYverf111 { get; set; }
        public int BYsmid112 { get; set; }
        public string BYcmdt112 { get; set; }
        public int BYverf112 { get; set; }
        public int BYsmid113 { get; set; }
        public string BYcmdt113 { get; set; }
        public int BYverf113 { get; set; }
        public int BYsmid114 { get; set; }
        public string BYcmdt114 { get; set; }
        public int BYverf114 { get; set; }
        public int BYsmid115 { get; set; }
        public string BYcmdt115 { get; set; }
        public int BYverf115 { get; set; }
        public int BYsmid116 { get; set; }
        public string BYcmdt116 { get; set; }
        public int BYverf116 { get; set; }
        public int BYsmid117 { get; set; }
        public string BYcmdt117 { get; set; }
        public int BYverf117 { get; set; }
        public int BYsmid118 { get; set; }
        public string BYcmdt118 { get; set; }
        public int BYverf118 { get; set; }
        public int BYsmid119 { get; set; }
        public string BYcmdt119 { get; set; }
        public int BYverf119 { get; set; }
        public int BYsmid120 { get; set; }
        public string BYcmdt120 { get; set; }
        public int BYverf120 { get; set; }
        public int BYsmid121 { get; set; }
        public string BYcmdt121 { get; set; }
        public int BYverf121 { get; set; }
        public int BYsmid122 { get; set; }
        public string BYcmdt122 { get; set; }
        public int BYverf122 { get; set; }
        public int BYsmid123 { get; set; }
        public string BYcmdt123 { get; set; }
        public int BYverf123 { get; set; }
        public int BYsmid124 { get; set; }
        public string BYcmdt124 { get; set; }
        public int BYverf124 { get; set; }
        public int BYsmid125 { get; set; }
        public string BYcmdt125 { get; set; }
        public int BYverf125 { get; set; }
        public string BYnote01 { get; set; }
        public string BYnote02 { get; set; }
        public string BYnote03 { get; set; }
        public string BYnote04 { get; set; }
        public string BYnote05 { get; set; }
        public string BYnote06 { get; set; }
        public string BYnote07 { get; set; }
        public string BYnote08 { get; set; }
        public string BYnote09 { get; set; }
        public string BYnote10 { get; set; }
        public string BYnote11 { get; set; }
        public string BYnote12 { get; set; }
        public string BYnote13 { get; set; }
        public string BYnote14 { get; set; }
        public string BYnote15 { get; set; }
        public string BYtask01 { get; set; }
        public string BYtask02 { get; set; }
        public string BYtask03 { get; set; }
        public string BYtask04 { get; set; }
        public string BYtask05 { get; set; }
        public string BYacit01 { get; set; }
        public string BYacit02 { get; set; }
        public string BYacit03 { get; set; }
        public string BYacit04 { get; set; }
        public string BYacit05 { get; set; }
        public string BYtool01 { get; set; }
        public string BYtool02 { get; set; }
        public string BYtool03 { get; set; }
        public string BYtool04 { get; set; }
        public string BYtool05 { get; set; }
        public string BYdocn01 { get; set; }
        public string BYdocn02 { get; set; }
        public string BYdocn03 { get; set; }
        public string BYdocn04 { get; set; }
        public string BYdocn05 { get; set; }
        public int BYprfx01 { get; set; }
        public int BYprfx02 { get; set; }
        public int BYprfx03 { get; set; }
        public int BYprfx04 { get; set; }
        public int BYprfx05 { get; set; }
        public string BYrate01 { get; set; }
        public string BYrate02 { get; set; }
        public string BYrate03 { get; set; }
        public string BYrate04 { get; set; }
        public string BYrate05 { get; set; }
        public string BYpref01 { get; set; }
        public string BYpref02 { get; set; }
        public string BYpref03 { get; set; }
        public string BYpref04 { get; set; }
        public string BYpref05 { get; set; }
        public string BYratd01 { get; set; }
        public string BYratd02 { get; set; }
        public string BYratd03 { get; set; }
        public string BYratd04 { get; set; }
        public string BYratd05 { get; set; }
        public int BYallch1c { get; set; }
        public int BYwekday { get; set; }
        public string BYwekdnm { get; set; }
        public bool BYchck { get; set; }
        public int BYchckid { get; set; }
        public string BYchcknm { get; set; }
        public string BYchckdt { get; set; }
        public int BYyyyy { get; set; }
        public int BYyyyymm { get; set; }
        public int BYweeknr { get; set; }
        public string BYweekds { get; set; }
        public int BYyyyymmdd { get; set; }
        public int BYhhmmss { get; set; }
        public string BYcrdt { get; set; }
        public string BYeddt { get; set; }
        public int BYcrusid { get; set; }
        public int BYedusid { get; set; }
        public string BYcrusnm { get; set; }
        public string BYedusnm { get; set; }
        public string BYcrdate { get; set; }




        public string CYID { get; set; }
        public int CYprojid { get; set; }
        public int CYtskoid { get; set; }
        public int CYdcgrid { get; set; }
        public int CYdctpid { get; set; }
        public int CYtspdid { get; set; }
        public int CYdistid { get; set; }
        public string CYdistnm { get; set; }
        public int CYacctid { get; set; }
        public int CYuserid { get; set; }
        public string CYusernm { get; set; }
        public int CYdimgid { get; set; }
        public string CYdimgnm { get; set; }
        public int CYsmid111 { get; set; }
        public string CYcmdt111 { get; set; }
        public int CYverf111 { get; set; }
        public int CYsmid112 { get; set; }
        public string CYcmdt112 { get; set; }
        public int CYverf112 { get; set; }
        public int CYsmid113 { get; set; }
        public string CYcmdt113 { get; set; }
        public int CYverf113 { get; set; }
        public int CYsmid114 { get; set; }
        public string CYcmdt114 { get; set; }
        public int CYverf114 { get; set; }
        public int CYsmid115 { get; set; }
        public string CYcmdt115 { get; set; }
        public int CYverf115 { get; set; }
        public int CYsmid116 { get; set; }
        public string CYcmdt116 { get; set; }
        public int CYverf116 { get; set; }
        public int CYsmid117 { get; set; }
        public string CYcmdt117 { get; set; }
        public int CYverf117 { get; set; }
        public int CYsmid118 { get; set; }
        public string CYcmdt118 { get; set; }
        public int CYverf118 { get; set; }
        public int CYsmid119 { get; set; }
        public string CYcmdt119 { get; set; }
        public int CYverf119 { get; set; }
        public int CYsmid120 { get; set; }
        public string CYcmdt120 { get; set; }
        public int CYverf120 { get; set; }
        public int CYsmid121 { get; set; }
        public string CYcmdt121 { get; set; }
        public int CYverf121 { get; set; }
        public int CYsmid122 { get; set; }
        public string CYcmdt122 { get; set; }
        public int CYverf122 { get; set; }
        public int CYsmid123 { get; set; }
        public string CYcmdt123 { get; set; }
        public int CYverf123 { get; set; }
        public int CYsmid124 { get; set; }
        public string CYcmdt124 { get; set; }
        public int CYverf124 { get; set; }
        public int CYsmid125 { get; set; }
        public string CYcmdt125 { get; set; }
        public int CYverf125 { get; set; }
        public string CYnote01 { get; set; }
        public string CYnote02 { get; set; }
        public string CYnote03 { get; set; }
        public string CYnote04 { get; set; }
        public string CYnote05 { get; set; }
        public string CYnote06 { get; set; }
        public string CYnote07 { get; set; }
        public string CYnote08 { get; set; }
        public string CYnote09 { get; set; }
        public string CYnote10 { get; set; }
        public string CYnote11 { get; set; }
        public string CYnote12 { get; set; }
        public string CYnote13 { get; set; }
        public string CYnote14 { get; set; }
        public string CYnote15 { get; set; }
        public string CYtask01 { get; set; }
        public string CYtask02 { get; set; }
        public string CYtask03 { get; set; }
        public string CYtask04 { get; set; }
        public string CYtask05 { get; set; }
        public string CYacit01 { get; set; }
        public string CYacit02 { get; set; }
        public string CYacit03 { get; set; }
        public string CYacit04 { get; set; }
        public string CYacit05 { get; set; }
        public string CYtool01 { get; set; }
        public string CYtool02 { get; set; }
        public string CYtool03 { get; set; }
        public string CYtool04 { get; set; }
        public string CYtool05 { get; set; }
        public string CYdocn01 { get; set; }
        public string CYdocn02 { get; set; }
        public string CYdocn03 { get; set; }
        public string CYdocn04 { get; set; }
        public string CYdocn05 { get; set; }
        public int CYprfx01 { get; set; }
        public int CYprfx02 { get; set; }
        public int CYprfx03 { get; set; }
        public int CYprfx04 { get; set; }
        public int CYprfx05 { get; set; }
        public string CYrate01 { get; set; }
        public string CYrate02 { get; set; }
        public string CYrate03 { get; set; }
        public string CYrate04 { get; set; }
        public string CYrate05 { get; set; }
        public string CYpref01 { get; set; }
        public string CYpref02 { get; set; }
        public string CYpref03 { get; set; }
        public string CYpref04 { get; set; }
        public string CYpref05 { get; set; }
        public string CYratd01 { get; set; }
        public string CYratd02 { get; set; }
        public string CYratd03 { get; set; }
        public string CYratd04 { get; set; }
        public string CYratd05 { get; set; }
        public int CYallch1c { get; set; }
        public int CYwekday { get; set; }
        public string CYwekdnm { get; set; }
        public bool CYchck { get; set; }
        public int CYchckid { get; set; }
        public string CYchcknm { get; set; }
        public string CYchckdt { get; set; }
        public int CYyyyy { get; set; }
        public int CYyyyymm { get; set; }
        public int CYweeknr { get; set; }
        public string CYweekds { get; set; }
        public int CYyyyymmdd { get; set; }
        public int CYhhmmss { get; set; }
        public string CYcrdt { get; set; }
        public string CYeddt { get; set; }
        public int CYcrusid { get; set; }
        public int CYedusid { get; set; }
        public string CYcrusnm { get; set; }
        public string CYedusnm { get; set; }
        public string CYcrdate { get; set; }


        public string DYID { get; set; }
        public int DYprojid { get; set; }
        public int DYtskoid { get; set; }
        public int DYdcgrid { get; set; }
        public int DYdctpid { get; set; }
        public int DYtspdid { get; set; }
        public int DYdistid { get; set; }
        public string DYdistnm { get; set; }
        public int DYacctid { get; set; }
        public int DYuserid { get; set; }
        public string DYusernm { get; set; }
        public int DYdimgid { get; set; }
        public string DYdimgnm { get; set; }
        public int DYsmid111 { get; set; }
        public string DYcmdt111 { get; set; }
        public int DYverf111 { get; set; }
        public int DYsmid112 { get; set; }
        public string DYcmdt112 { get; set; }
        public int DYverf112 { get; set; }
        public int DYsmid113 { get; set; }
        public string DYcmdt113 { get; set; }
        public int DYverf113 { get; set; }
        public int DYsmid114 { get; set; }
        public string DYcmdt114 { get; set; }
        public int DYverf114 { get; set; }
        public int DYsmid115 { get; set; }
        public string DYcmdt115 { get; set; }
        public int DYverf115 { get; set; }
        public int DYsmid116 { get; set; }
        public string DYcmdt116 { get; set; }
        public int DYverf116 { get; set; }
        public int DYsmid117 { get; set; }
        public string DYcmdt117 { get; set; }
        public int DYverf117 { get; set; }
        public int DYsmid118 { get; set; }
        public string DYcmdt118 { get; set; }
        public int DYverf118 { get; set; }
        public int DYsmid119 { get; set; }
        public string DYcmdt119 { get; set; }
        public int DYverf119 { get; set; }
        public int DYsmid120 { get; set; }
        public string DYcmdt120 { get; set; }
        public int DYverf120 { get; set; }
        public int DYsmid121 { get; set; }
        public string DYcmdt121 { get; set; }
        public int DYverf121 { get; set; }
        public int DYsmid122 { get; set; }
        public string DYcmdt122 { get; set; }
        public int DYverf122 { get; set; }
        public int DYsmid123 { get; set; }
        public string DYcmdt123 { get; set; }
        public int DYverf123 { get; set; }
        public int DYsmid124 { get; set; }
        public string DYcmdt124 { get; set; }
        public int DYverf124 { get; set; }
        public int DYsmid125 { get; set; }
        public string DYcmdt125 { get; set; }
        public int DYverf125 { get; set; }
        public string DYnote01 { get; set; }
        public string DYnote02 { get; set; }
        public string DYnote03 { get; set; }
        public string DYnote04 { get; set; }
        public string DYnote05 { get; set; }
        public string DYnote06 { get; set; }
        public string DYnote07 { get; set; }
        public string DYnote08 { get; set; }
        public string DYnote09 { get; set; }
        public string DYnote10 { get; set; }
        public string DYnote11 { get; set; }
        public string DYnote12 { get; set; }
        public string DYnote13 { get; set; }
        public string DYnote14 { get; set; }
        public string DYnote15 { get; set; }
        public string DYtask01 { get; set; }
        public string DYtask02 { get; set; }
        public string DYtask03 { get; set; }
        public string DYtask04 { get; set; }
        public string DYtask05 { get; set; }
        public string DYacit01 { get; set; }
        public string DYacit02 { get; set; }
        public string DYacit03 { get; set; }
        public string DYacit04 { get; set; }
        public string DYacit05 { get; set; }
        public string DYtool01 { get; set; }
        public string DYtool02 { get; set; }
        public string DYtool03 { get; set; }
        public string DYtool04 { get; set; }
        public string DYtool05 { get; set; }
        public string DYdocn01 { get; set; }
        public string DYdocn02 { get; set; }
        public string DYdocn03 { get; set; }
        public string DYdocn04 { get; set; }
        public string DYdocn05 { get; set; }
        public int DYprfx01 { get; set; }
        public int DYprfx02 { get; set; }
        public int DYprfx03 { get; set; }
        public int DYprfx04 { get; set; }
        public int DYprfx05 { get; set; }
        public string DYrate01 { get; set; }
        public string DYrate02 { get; set; }
        public string DYrate03 { get; set; }
        public string DYrate04 { get; set; }
        public string DYrate05 { get; set; }
        public string DYpref01 { get; set; }
        public string DYpref02 { get; set; }
        public string DYpref03 { get; set; }
        public string DYpref04 { get; set; }
        public string DYpref05 { get; set; }
        public string DYratd01 { get; set; }
        public string DYratd02 { get; set; }
        public string DYratd03 { get; set; }
        public string DYratd04 { get; set; }
        public string DYratd05 { get; set; }
        public int DYallch1c { get; set; }
        public int DYwekday { get; set; }
        public string DYwekdnm { get; set; }
        public bool DYchck { get; set; }
        public int DYchckid { get; set; }
        public string DYchcknm { get; set; }
        public string DYchckdt { get; set; }
        public int DYyyyy { get; set; }
        public int DYyyyymm { get; set; }
        public int DYweeknr { get; set; }
        public string DYweekds { get; set; }
        public int DYyyyymmdd { get; set; }
        public int DYhhmmss { get; set; }
        public string DYcrdt { get; set; }
        public string DYeddt { get; set; }
        public int DYcrusid { get; set; }
        public int DYedusid { get; set; }
        public string DYcrusnm { get; set; }
        public string DYedusnm { get; set; }
        public string DYcrdate { get; set; }

        public string EYID { get; set; }
        public int EYprojid { get; set; }
        public int EYtskoid { get; set; }
        public int EYdcgrid { get; set; }
        public int EYdctpid { get; set; }
        public int EYtspdid { get; set; }
        public int EYdistid { get; set; }
        public string EYdistnm { get; set; }
        public int EYacctid { get; set; }
        public int EYuserid { get; set; }
        public string EYusernm { get; set; }
        public int EYdimgid { get; set; }
        public string EYdimgnm { get; set; }
        public int EYsmid111 { get; set; }
        public string EYcmdt111 { get; set; }
        public int EYverf111 { get; set; }
        public int EYsmid112 { get; set; }
        public string EYcmdt112 { get; set; }
        public int EYverf112 { get; set; }
        public int EYsmid113 { get; set; }
        public string EYcmdt113 { get; set; }
        public int EYverf113 { get; set; }
        public int EYsmid114 { get; set; }
        public string EYcmdt114 { get; set; }
        public int EYverf114 { get; set; }
        public int EYsmid115 { get; set; }
        public string EYcmdt115 { get; set; }
        public int EYverf115 { get; set; }
        public int EYsmid116 { get; set; }
        public string EYcmdt116 { get; set; }
        public int EYverf116 { get; set; }
        public int EYsmid117 { get; set; }
        public string EYcmdt117 { get; set; }
        public int EYverf117 { get; set; }
        public int EYsmid118 { get; set; }
        public string EYcmdt118 { get; set; }
        public int EYverf118 { get; set; }
        public int EYsmid119 { get; set; }
        public string EYcmdt119 { get; set; }
        public int EYverf119 { get; set; }
        public int EYsmid120 { get; set; }
        public string EYcmdt120 { get; set; }
        public int EYverf120 { get; set; }
        public int EYsmid121 { get; set; }
        public string EYcmdt121 { get; set; }
        public int EYverf121 { get; set; }
        public int EYsmid122 { get; set; }
        public string EYcmdt122 { get; set; }
        public int EYverf122 { get; set; }
        public int EYsmid123 { get; set; }
        public string EYcmdt123 { get; set; }
        public int EYverf123 { get; set; }
        public int EYsmid124 { get; set; }
        public string EYcmdt124 { get; set; }
        public int EYverf124 { get; set; }
        public int EYsmid125 { get; set; }
        public string EYcmdt125 { get; set; }
        public int EYverf125 { get; set; }
        public string EYnote01 { get; set; }
        public string EYnote02 { get; set; }
        public string EYnote03 { get; set; }
        public string EYnote04 { get; set; }
        public string EYnote05 { get; set; }
        public string EYnote06 { get; set; }
        public string EYnote07 { get; set; }
        public string EYnote08 { get; set; }
        public string EYnote09 { get; set; }
        public string EYnote10 { get; set; }
        public string EYnote11 { get; set; }
        public string EYnote12 { get; set; }
        public string EYnote13 { get; set; }
        public string EYnote14 { get; set; }
        public string EYnote15 { get; set; }
        public string EYtask01 { get; set; }
        public string EYtask02 { get; set; }
        public string EYtask03 { get; set; }
        public string EYtask04 { get; set; }
        public string EYtask05 { get; set; }
        public string EYacit01 { get; set; }
        public string EYacit02 { get; set; }
        public string EYacit03 { get; set; }
        public string EYacit04 { get; set; }
        public string EYacit05 { get; set; }
        public string EYtool01 { get; set; }
        public string EYtool02 { get; set; }
        public string EYtool03 { get; set; }
        public string EYtool04 { get; set; }
        public string EYtool05 { get; set; }
        public string EYdocn01 { get; set; }
        public string EYdocn02 { get; set; }
        public string EYdocn03 { get; set; }
        public string EYdocn04 { get; set; }
        public string EYdocn05 { get; set; }
        public int EYprfx01 { get; set; }
        public int EYprfx02 { get; set; }
        public int EYprfx03 { get; set; }
        public int EYprfx04 { get; set; }
        public int EYprfx05 { get; set; }
        public string EYrate01 { get; set; }
        public string EYrate02 { get; set; }
        public string EYrate03 { get; set; }
        public string EYrate04 { get; set; }
        public string EYrate05 { get; set; }
        public string EYpref01 { get; set; }
        public string EYpref02 { get; set; }
        public string EYpref03 { get; set; }
        public string EYpref04 { get; set; }
        public string EYpref05 { get; set; }
        public string EYratd01 { get; set; }
        public string EYratd02 { get; set; }
        public string EYratd03 { get; set; }
        public string EYratd04 { get; set; }
        public string EYratd05 { get; set; }
        public int EYallch1c { get; set; }
        public int EYwekday { get; set; }
        public string EYwekdnm { get; set; }
        public bool EYchck { get; set; }
        public int EYchckid { get; set; }
        public string EYchcknm { get; set; }
        public string EYchckdt { get; set; }
        public int EYyyyy { get; set; }
        public int EYyyyymm { get; set; }
        public int EYweeknr { get; set; }
        public string EYweekds { get; set; }
        public int EYyyyymmdd { get; set; }
        public int EYhhmmss { get; set; }
        public string EYcrdt { get; set; }
        public string EYeddt { get; set; }
        public int EYcrusid { get; set; }
        public int EYedusid { get; set; }
        public string EYcrusnm { get; set; }
        public string EYedusnm { get; set; }
        public string EYcrdate { get; set; }
        

    }
}
